config/routes.rb
Rails.application.routes.draw do
  resources :mini_urls

  get '/', to: 'mini_urls#new'

  get '/:short_url', to: 'mini_urls#open'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip.rb
class Ip < ApplicationRecord
  belongs_to :mini_url
end

app/models/mini_url.rb
URL_LENGTH = 5

class MiniUrl < ApplicationRecord
  has_many :ip
  before_create :generate_mini_url
  validates :full_url, :url => true

  def num_visits
    Ip.where(:mini_url_id => self.id).sum(:num_visits)
  end

  private

  def generate_mini_url

    # generate a random string of URL_LENGTH chars. Continue loop
    # until a unique one is found.
    loop do
      self.short_url = SecureRandom.alphanumeric(URL_LENGTH)

      if ! MiniUrl.exists?(short_url: self.short_url)
        break
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mini_urls_controller.rb
class MiniUrlsController < ApplicationController
  before_action :set_mini_url, only: [:show, :edit, :update, :destroy, :open]

  # GET /mini_urls
  # GET /mini_urls.json
  def index
    @mini_urls = MiniUrl.all
  end

  # GET /mini_urls/1
  # GET /mini_urls/1.json
  def show
    @ips = Ip.where(:mini_url_id => @mini_url.id).select(:ip, :num_visits)
  end

  # GET /mini_urls/new
  def new
    @mini_url = MiniUrl.new
  end

  # GET /mini_urls/1/edit
  def edit
  end

  # GET /:short_url
  def open
    if Ip.exists?(ip:request.remote_ip, mini_url_id: @mini_url.id)
      # this link has been followed before by this IP. Increment visit counter
      @ip = Ip.find_by ip: request.remote_ip, mini_url_id: @mini_url.id
      @ip.update(num_visits: @ip.num_visits + 1)
    else
      # either this link has never been followed, or it's a new IP. Either 
      # way, add new record to Ip table
      @ip = Ip.create(:ip => request.remote_ip,
                      :num_visits => 1,
                      :mini_url_id => @mini_url.id)
      end

      redirect_to @mini_url.full_url
  end

  # POST /mini_urls
  # POST /mini_urls.json
  def create
    @mini_url = MiniUrl.new(mini_url_params)

    respond_to do |format|
      if @mini_url.save
        format.html { redirect_to @mini_url, notice: 'Mini url was successfully created.' }
        format.json { render :show, status: :created, location: @mini_url }
      else
        format.html { render :new }
        format.json { render json: @mini_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mini_urls/1
  # PATCH/PUT /mini_urls/1.json
  def update
    respond_to do |format|
      if @mini_url.update(mini_url_params)
        format.html { redirect_to @mini_url, notice: 'Mini url was successfully updated.' }
        format.json { render :show, status: :ok, location: @mini_url }
      else
        format.html { render :edit }
        format.json { render json: @mini_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mini_urls/1
  # DELETE /mini_urls/1.json
  def destroy
    @mini_url.destroy
    respond_to do |format|
      format.html { redirect_to mini_urls_url, notice: 'Mini url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mini_url
      if ! params[:id].nil?
        @mini_url = MiniUrl.find(params[:id])
      elsif ! params[:short_url].nil?
        @mini_url = MiniUrl.find_by short_url: params[:short_url] 
      end
    end

    # Only allow a list of trusted parameters through.
    def mini_url_params
      params.require(:mini_url).permit(:short_url, :full_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mini_urls_helper.rb
module MiniUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniurl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mini_urls/_form.html.erb
<%= form_with(model: mini_url, local: true) do |form| %>
  <% if mini_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mini_url.errors.count, "error") %> prohibited this mini_url from being saved:</h2>

      <ul>
      <% mini_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_url %>
    <%= form.text_area :full_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mini_urls/edit.html.erb
<h1>Editing Mini Url</h1>

<%= render 'form', mini_url: @mini_url %>

<%= link_to 'Show', @mini_url %> |
<%= link_to 'Back', mini_urls_path %>

app/views/mini_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mini Urls</h1>

<table>
  <thead>
    <tr>
      <th>Short url</th>
      <th>Full url</th>
      <th>Num Visits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mini_urls.each do |mini_url| %>
      <tr>
        <td><%= link_to mini_url.short_url, request.protocol + request.env["HTTP_HOST"] + '/' + mini_url.short_url %></td>
        <td><%= link_to mini_url.full_url, mini_url.full_url %></td>
        <td><%= mini_url.num_visits %></td>
        <td><%= link_to 'Show', mini_url %></td>
        <td><%= link_to 'Edit', edit_mini_url_path(mini_url) %></td>
        <td><%= link_to 'Destroy', mini_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mini Url', new_mini_url_path %>

app/views/mini_urls/new.html.erb
<h1>Mini-ify a Url</h1>

<%= render 'form', mini_url: @mini_url %>

<%= link_to 'MiniURL Index', mini_urls_path %>

app/views/mini_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short url:</strong>
  <%= @mini_url.short_url %>
</p>

<p>
  <strong>Full url:</strong>
  <%= @mini_url.full_url %>
</p>

<p>
  <strong>Total Visits:</strong>
  <%= @mini_url.num_visits %>
</p>

<p>
  <strong>Visitor History:</strong>
  <table>
    <thead>
      <tr>
        <th>IP Address</th>
        <th>Visits</th>
      </tr>
    </thead>
    <tbody>
      <% if ! @ips.nil? %>
      <% @ips.each do |ip| %>
        <tr>
          <td><%= ip.ip %></td>
          <td><%= ip.num_visits %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</p>

<%= social_share_button_tag(@mini_url.short_url) %>

<%= link_to 'Edit', edit_mini_url_path(@mini_url) %> |
<%= link_to 'Back', mini_urls_path %>